version: '3.8'

services:
  courtroom:
    build: .
    container_name: courtroom_app
    ports:
      - "3000:3000"

    # Load environment variables from .env file
    env_file:
      - .env

    # Keep NODE_ENV, remove the hardcoded DATABASE_URL
    environment:
      NODE_ENV: production

    volumes:
      - .:/app
      - /app/node_modules

    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             npm run build &&
             npm run start"


    restart: unless-stopped
