import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      
<header style={{ position: "fixed", left: 8, top: 8, zIndex: 1000 }}>
  <div style={{ background: "#fff", padding: "4px 8px", borderRadius: 6, fontSize: 12 }}>
    Student Rollno: <strong>20900837</strong>
  </div>
</header>
<main style={{ paddingTop: 48 }}>{children}</main>

      </body>
    </html>
  );
}
